### ISSUE TITLE
Add support for removing status tab

### ISSUE THREAD

**Issue by daedroza** [Schwartzblat/WhatsAppPatcher#14]
Would it be possible for you to add support for removing status tab? Also additional learning resources on how to identify smali elements for UI would be greatly appreciated!

**Comment by Schwartzblat** [comment]
Yeah it is possible I can make it configurable maybe I just need to research the tab mechanism.
About the learning resources- I will make a guide if I will have time for this.

**Comment by daedroza** [comment]
For tab mechanism, I have done some research. Here is a Xposed Extension that dynamically modifies the smali bytecode - https://github.com/suraj0208/WhatsappExtensions/blob/0c4b130eb0b57f3193ca6ed8391f11b14ddc3763/app/src/main/java/com/suraj/waext/ExtModule.java#L1283

I still don't know how we can hook the View before it is inflated so that we can remove the UI component.

**Comment by Schwartzblat** [comment]
Good job for the research. I will take a look on it.
