### ISSUE TITLE
Usage command not work

### ISSUE THREAD

**Issue by Emanuele-1998** [Schwartzblat/WhatsAppPatcher#18]
The command not work, I use Termux for usage, python is installed

![Screenshot_20230419_111319_Termux](https://user-images.githubusercontent.com/67318166/233028248-bd9c302b-4b99-49f4-a361-49d7b591276e.jpg)

**Comment by Schwartzblat** [comment]
Looks like you wrote the wrong path. Try this one:
`python WhatsAppPatcher/whatsapp_patcher/main.py...`

**Comment by Emanuele-1998** [comment]
Not work, can't open file
