### ISSUE TITLE
Something is wrong with your version of WhatsApp

### ISSUE THREAD

**Issue by bduunity** [Schwartzblat/WhatsAppPatcher#23]
Successfully patched but after entering phone number alerting error Something is wrong with your version of WhatsApp

**Comment by almtwakel** [comment]
نفس المشكلة
هناك خطأ ما في إصدار WhatsApp الخاص بك

**Comment by Schwartzblat** [comment]
I am working on it.

**Comment by Schwartzblat** [comment]
@almtwakel @bduunity Fixed.
https://github.com/Schwartzblat/WhatsAppPatcher/releases/tag/1.0.9
