### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ghost** [Schwartzblat/WhatsAppPatcher#34]
I'm trying to patch the WhatsApp apk but get the following error:

![kqOwS](https://github.com/Schwartzblat/WhatsAppPatcher/assets/145134894/edce23d5-8003-47a1-978d-04e72a340f8a)

Would be awesome if somebody has an idead on how to fix it.

**Comment by s0umitra** [comment]
run this command: `python main.py -p ./WhatsApp.apk -o PatchedWhatsApp.apk`
under parent directory.

main.py is present in parent directory and not in subdirectory "whatsapp_patcher".

**Comment by Schwartzblat** [comment]
You got your answer, I am closing the issue.
