### ISSUE TITLE
repeatably crashing 1.0.9

### ISSUE THREAD

**Issue by naive890** [Schwartzblat/WhatsAppPatcher#35]
hi the latest version on this crashes repeatably  and no natural fix to crashing works...please help out if u can., thankyou

**Comment by Schwartzblat** [comment]
Fixed.

**Comment by FahadBinHussain** [comment]
Could you please clarify your statement about "fixed"? What specifically was fixed? I'm currently experiencing issues with the app crashing on Xiaomi 11i HyperCharge.

**Comment by FahadBinHussain** [comment]
> Fixed.

Could you please clarify your statement about "fixed"? What specifically was fixed? I'm currently experiencing issues with the app crashing on Xiaomi 11i HyperCharge.

**Comment by jeverling** [comment]
> Fixed.

Hi Alon, could you please provide the latest version of WhatsApp the patcher works with?
Thanks a lot!

**Comment by jeverling** [comment]
I can confirm that I was able to patch version `2.23.19.78` with the latest commit (`aa90bb5`) and RevokedMessagePatch works as expected.
Amazing! Thanks a lot! :)
