### ISSUE TITLE
Patch and release apk with GitHub Actions

### ISSUE THREAD

**Issue by JohnBetaro** [Schwartzblat/WhatsAppPatcher#38]
Hi, the title says it all, this will make the process faster for updates, and we also don't have to trust anyone because there will be no human intervention.

I hope you'll consider my suggestion. Thank you.

**Comment by Schwartzblat** [comment]
That's a good idea, I will look into it.

**Comment by Schwartzblat** [comment]
Done with the help of @jeverling
