### ISSUE TITLE
Cannot verify number

### ISSUE THREAD

**Issue by s0umitra** [Schwartzblat/WhatsAppPatcher#44]
Can't get my number verified (location- India)

Tried with both packages (+cleared cache/storage)
Released apk: [PatchedWhatapp](https://github.com/Schwartzblat/WhatsAppPatcher/releases/download/1.0.11/PatchedWhatsApp.apk)
and locally patched apk (original downloaded from https://www.whatsapp.com/android/)

Mobile Snapshot-
![Screenshot_20230927-115140_WhatsApp](https://github.com/Schwartzblat/WhatsAppPatcher/assets/44529322/3efbfb82-a606-431f-b124-42e2ba3935b6)

Patching logs-
![image](https://github.com/Schwartzblat/WhatsAppPatcher/assets/44529322/7e1df52e-16f0-40d7-98ae-2f040e969efa)

**Comment by jeverling** [comment]
Strange, it worked for me, but using commit `aa90bb5` and patching `2.23.19.78` locally.
Maybe WhatsApp released a new version in the meantime that changed something?

**Comment by s0umitra** [comment]
@jeverling tried again, using latest master pull with [WhatsApp 2.23.19.77 (stable) ](https://www.apkmirror.com/apk/whatsapp-inc/whatsapp/whatsapp-2-23-19-77-release/whatsapp-messenger-2-23-19-77-android-apk-download/)
Still getting "_Something is wrong_" error on verification screen.

**Comment by s0umitra** [comment]
Okay, using aa90bb5 with 2.23.19.78, **I am able to verify the number**.
Thankyou!

**Comment by s0umitra** [comment]
Closing this issue.
