### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by TorCzaf** [Schwartzblat/WhatsAppPatcher#46]
Hi I would like to know how to install whatsapp patcher (step by step) please.

I downloaded "PatchedWhatsApp.apk" then I tried to install it and got "App not installed" error

Are these are the exact apps that I need?
![Screenshot_20230927-221052_Google Play Store](https://github.com/Schwartzblat/WhatsAppPatcher/assets/137301636/704ba7c7-b197-43ea-8474-0e80b14b989c)
![Screenshot_20230927-221025_Google Play Store](https://github.com/Schwartzblat/WhatsAppPatcher/assets/137301636/fecaae7a-cf95-40da-9118-28fe6563e1df)

And how do I use these commands?
`git clone https://github.com/Schwartzblat/WhatsAppPatcher.git`

`pip install -r requirements.txt`

`python whatsapp_patcher/main.py -p ./WhatsApp.apk -o PatchedWhatsApp.apk`

And do I need to have WhatsApp.apk file?

Thank you.

**Comment by Schwartzblat** [comment]
You can use termux but if you are getting in trouble, just download the apk from my releases.
