### ISSUE TITLE
latest release is being flagged as malicious by virus checkers

### ISSUE THREAD

**Issue by naive890** [Schwartzblat/WhatsAppPatcher#50]
The latest release of the patch is being flagged as malicious by various virus checkers on my phone. Specifically, it is being flagged as a Trojan.

This Trojan flag was not present on previous releases of the modded APK.

I have not checked the source code of the APK, but I am happy to do so if that would be helpful.

Thank you for your contribution to this project. Please investigate this issue. thankyou, :)

**Comment by Schwartzblat** [comment]
What the hell hahaha.
What virus checker are you using?
Maybe they added some kind of a hash check for popular apps (?)

**Comment by jeverling** [comment]
Same for me! The weird thing is that I went back to the combination of version `2.23.19.78` with commit `aa90bb5`, and I got the warning after installing that apk as well, even though I didn't get it before. So the explanation that there is now a check for the hash of WhatsApp makes sense.

I'm not sure what is raising this warning, my phone is a Huawei but really old (Honor 6x), I'm pretty sure there aren't any vendor updates for that model. I'm also not running any anti virus apps, so probably it's something Google added.

<img src="https://github.com/Schwartzblat/WhatsAppPatcher/assets/121946/c4fd9eb5-7687-46e5-9fa4-89b328853da8" width="450" height="800">

**Comment by naive890** [comment]
> What the hell hahaha. What virus checker are you using? Maybe they added some kind of a hash check for popular apps (?)

i tried installing on realme (color os) and xiaomi (miUI) both of which flagged it as trojan. also play protect stoopped the installation by default which tbh it does for most external apks. but play protect didnt flag WhatsApp patchers previous versions and stopped installation

**Comment by naive890** [comment]
i tried installing on realme (color os) and xiaomi (miUI) both of which flagged it as trojan. also play protect stoopped the installation by default which tbh it does for most external apks. but play protect didnt flag WhatsApp patchers previous versions and stopped installation

**Comment by Schwartzblat** [comment]
Can you download an old version of my patcher and tell me if it's being flagged too?

**Comment by naive890** [comment]
I've installed four other versions of your patcher and I can assure you that none of them were flagged. Rest assured, the app works just fine.
