### ISSUE TITLE
 Compiling the smali with apktool Error - There is already a label with that name.

### ISSUE THREAD

**Issue by HoshenKadosh** [Schwartzblat/WhatsAppPatcher#52]
the command i ran:
`python3 main.py --ab-tests`

the error i got:
`xtracted/smali_classes2/X/2lr.3.smali[2283,4] There is already a label with that name.
Could not smali file: X/2lr.3.smali
Traceback (most recent call last):
  File "/Users/hoshenkadosh/Downloads/WhatsAppPatcher/main.py", line 44, in <module>
    main()
  File "/Users/hoshenkadosh/Downloads/WhatsAppPatcher/main.py", line 38, in main
    extractor.compile_smali()
  File "/Users/hoshenkadosh/Downloads/WhatsAppPatcher/whatsapp_patcher/extractor.py", line 61, in compile_smali
    subprocess.check_call(command, timeout=20 * 60)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '/Users/hoshenkadosh/Downloads/WhatsAppPatcher/bin/apktool_2.7.0.jar', '-q', 'build', '--use-aapt2', './extracted', '--output', 'PatchedWhatsApp.apk']' returned non-zero exit status 1.
`

**Comment by shifoc** [comment]
I have the same error

**Comment by Schwartzblat** [comment]
I will try to fix it now.

**Comment by Schwartzblat** [comment]
Fixed, please let me know if it actually works.

**Comment by shifoc** [comment]
> Fixed, please let me know if it actually works.

The app compiled but I am unabled to open it

**Comment by shifoc** [comment]
> Fixed, please let me know if it actually works.

@Schwartzblat is it possible it's not enabling all the ab props? I think some are missing

**Comment by Schwartzblat** [comment]
Yep, there are 3 ab tests that I have defined them as "BAD_TESTS" because some of them cause the app to crash in the past.
I will be very happy if you will try to enable them by deleting them from the array and rerun the program and see if the app is crashing.

**Comment by shifoc** [comment]
> Yep, there are 3 ab tests that I have defined them as "BAD_TESTS" because some of them cause the app to crash in the past.
> I will be very happy if you will try to enable them by deleting them from the array and rerun the program and see if the app is crashing.

I think only the last one worked for me without crashing but I don't know what it does
