### ISSUE TITLE
update request.

### ISSUE THREAD

**Issue by naive890** [Schwartzblat/WhatsAppPatcher#65]
hi, so the latest patch of whatsapp patcher has been working flawlessly ever since the release but i think the current patched version of app is set to expire in a few. i would love i this patcher can receive the updates as it is really helpful to me and to many others. thanks again for all the efforts.

**Comment by Schwartzblat** [comment]
Hi,
I just created a new release, please let me know if it's working as usual.

**Comment by naive890** [comment]
hi, i just installed the patch and its working alright. I've checked most of the stuff i use everything works just fine. also the trojan flag from last patch is no more there. thanks for updating.

**Comment by jeverling** [comment]
Do you guys just install the newest APK over the older version? I was always uninstalling first and then restoring the backup, but maybe that's unnecessary.

**Comment by naive890** [comment]
Nah i just update the existing mod app, works just fine.

**Comment by jeverling** [comment]
Cool thanks for confirming!
