### ISSUE TITLE
upadte for the patcher

### ISSUE THREAD

**Issue by naive890** [Schwartzblat/WhatsAppPatcher#81]
so the current version of patcher has stopped working as on 29-1-2024 (the version became out dated). which is unusual as the last issue was barely over a month ago.  thanks for your time and effort into this project. looking forward to the update.

**Comment by Schwartzblat** [comment]
I recompiled it, let me know if it helped.

**Comment by naive890** [comment]
yeah updated the app, i checked it seems to work alright. 
Thanks.
