### ISSUE TITLE
My whatsapp acc has been Suspended

### ISSUE THREAD

**Issue by Shinchannnnnn** [Schwartzblat/WhatsAppPatcher#84]
Hello guys, can anyone help me to recover my whatsapp account?
Is this possible?
Pls let me know if anything is there to recover my account.

![26fbacef-b4e8-4082-8cb4-5b4ff0d9042b](https://github.com/Schwartzblat/WhatsAppPatcher/assets/158838430/934e4008-00f2-454f-aa23-62498a612893)

**Comment by Schwartzblat** [comment]
Not relevant to this repo.
We discussed it in other issue.
